In [82]:
import pandas as pd
from pandas import get_dummies
import numpy as numpy
import sklearn
import xgboost

pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_rows', None)

In [83]:
df = pd.read_csv('/Users/kayodew/Desktop/supply_chain_ml_project/DataCoSupplyChainDataset.csv',encoding="latin1")

# 01 Data Understanding

In [84]:
df.head(10)

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,Customer Country,Customer Email,Customer Fname,Customer Id,Customer Lname,Customer Password,Customer Segment,Customer State,Customer Street,Customer Zipcode,Department Id,Department Name,Latitude,Longitude,Market,Order City,Order Country,Order Customer Id,order date (DateOrders),Order Id,Order Item Cardprod Id,Order Item Discount,Order Item Discount Rate,Order Item Id,Order Item Product Price,Order Item Profit Ratio,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Region,Order State,Order Status,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,Puerto Rico,XXXXXXXXX,Cally,20755,Holloway,XXXXXXXXX,Consumer,PR,5365 Noble Nectar Island,725.0,2,Fitness,18.251453,-66.037056,Pacific Asia,Bekasi,Indonesia,20755,1/31/2018 22:56,77202,1360,13.110000,0.04,180517,327.75,0.29,1,327.75,314.640015,91.250000,Southeast Asia,Java Occidental,COMPLETE,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,Puerto Rico,XXXXXXXXX,Irene,19492,Luna,XXXXXXXXX,Consumer,PR,2679 Rustic Loop,725.0,2,Fitness,18.279451,-66.037064,Pacific Asia,Bikaner,India,19492,1/13/2018 12:27,75939,1360,16.389999,0.05,179254,327.75,-0.80,1,327.75,311.359985,-249.089996,South Asia,Rajastán,PENDING,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,EE. UU.,XXXXXXXXX,Gillian,19491,Maldonado,XXXXXXXXX,Consumer,CA,8510 Round Bear Gate,95125.0,2,Fitness,37.292233,-121.881279,Pacific Asia,Bikaner,India,19491,1/13/2018 12:06,75938,1360,18.030001,0.06,179253,327.75,-0.80,1,327.75,309.720001,-247.779999,South Asia,Rajastán,CLOSED,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,EE. UU.,XXXXXXXXX,Tana,19490,Tate,XXXXXXXXX,Home Office,CA,3200 Amber Bend,90027.0,2,Fitness,34.125946,-118.291016,Pacific Asia,Townsville,Australia,19490,1/13/2018 11:45,75937,1360,22.940001,0.07,179252,327.75,0.08,1,327.75,304.809998,22.860001,Oceania,Queensland,COMPLETE,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,Puerto Rico,XXXXXXXXX,Orli,19489,Hendricks,XXXXXXXXX,Corporate,PR,8671 Iron Anchor Corners,725.0,2,Fitness,18.253769,-66.037048,Pacific Asia,Townsville,Australia,19489,1/13/2018 11:24,75936,1360,29.500000,0.09,179251,327.75,0.45,1,327.75,298.250000,134.210007,Oceania,Queensland,PENDING_PAYMENT,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class
5,TRANSFER,6,4,18.580000,294.980011,Shipping canceled,0,73,Sporting Goods,Tonawanda,EE. UU.,XXXXXXXXX,Kimberly,19488,Flowers,XXXXXXXXX,Consumer,NY,2122 Hazy Corner,14150.0,2,Fitness,43.013969,-78.879066,Pacific Asia,Toowoomba,Australia,19488,1/13/2018 11:03,75935,1360,32.779999,0.10,179250,327.75,0.06,1,327.75,294.980011,18.580000,Oceania,Queensland,CANCELED,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/19/2018 11:03,Standard Class
6,DEBIT,2,1,95.180000,288.420013,Late delivery,1,73,Sporting Goods,Caguas,Puerto Rico,XXXXXXXXX,Constance,19487,Terrell,XXXXXXXXX,Home Office,PR,1879 Green Pine Bank,725.0,2,Fitness,18.242538,-66.037056,Pacific Asia,Guangzhou,China,19487,1/13/2018 10:42,75934,1360,39.330002,0.12,179249,327.75,

In [85]:
# let's see how many rows and cols exist in the da.
print(df.shape[0])
print(df.shape[1])

180519
53


In [86]:
#Trick to tell a quick summary of the data.

pd.DataFrame({
    'column': df.columns,
    'dtype': df.dtypes.astype(str),
    'non_null_count': df.count().values,
    'missing_count': df.isnull().sum().values,
    'unique_values': df.nunique().values
})

,column,dtype,non_null_count,missing_count,unique_values
Type,Type,object,180519,0,4
Days for shipping (real),Days for shipping (real),int64,180519,0,7
Days for shipment (scheduled),Days for shipment (scheduled),int64,180519,0,4
Benefit per order,Benefit per order,float64,180519,0,21998
Sales per customer,Sales per customer,float64,180519,0,2927
Delivery Status,Delivery Status,object,180519,0,4
Late_delivery_risk,Late_delivery_risk,int64,180519,0,2
Category Id,Category Id,int64,180519,0,51
Category Name,Category Name,object,180519,0,50
Customer City,Customer City,object,180519,0,563


### Checking Null Fields

In [87]:
df.isnull().sum().sort_values(ascending = False)

Product Description              180519
Order Zipcode                    155679
Customer Lname                        8
Customer Zipcode                      3
Type                                  0
Order Profit Per Order                0
Order Item Cardprod Id                0
Order Item Discount                   0
Order Item Discount Rate              0
Order Item Id                         0
Order Item Product Price              0
Order Item Profit Ratio               0
Order Item Quantity                   0
Sales                                 0
Order Item Total                      0
Order Region                          0
order date (DateOrders)               0
Order State                           0
Order Status                          0
Product Card Id                       0
Product Category Id                   0
Product Image                         0
Product Name                          0
Product Price                         0
Product Status                        0


All these fields would be handled once we hit the drop phase of this project which means the dataset is fairly clean for the project.

# 02 DATA CLEANING

In [88]:
# Trick to quickly spot high and low  cardinality fields 
df.nunique().sort_values(ascending=False)

Order Item Id                    180519
Order Id                          65752
order date (DateOrders)           65752
shipping date (DateOrders)        63701
Benefit per order                 21998
Order Profit Per Order            21998
Order Customer Id                 20652
Customer Id                       20652
Latitude                          11250
Customer Street                    7458
Longitude                          4487
Order City                         3597
Order Item Total                   2927
Sales per customer                 2927
Customer Lname                     1109
Order State                        1089
Order Item Discount                1017
Customer Zipcode                    995
Customer Fname                      782
Order Zipcode                       609
Customer City                       563
Sales                               193
Order Country                       164
Order Item Profit Ratio             162
Product Card Id                     118


In [89]:
# Trying to understand what some firlds contain might give us a good understanding of what to drop or keep
df['Product Name'].unique()
df['Category Name'].unique() #or .nunique to see the count of unique values


array(['Sporting Goods', 'Cleats', 'Shop By Sport', "Women's Apparel",
       'Electronics', 'Boxing & MMA', 'Cardio Equipment', 'Trade-In',
       "Kids' Golf Clubs", 'Hunting & Shooting', 'Baseball & Softball',
       "Men's Footwear", 'Camping & Hiking', 'Consumer Electronics',
       'Cameras ', 'Computers', 'Basketball', 'Soccer', "Girls' Apparel",
       'Accessories', "Women's Clothing", 'Crafts', "Men's Clothing",
       'Tennis & Racquet', 'Fitness Accessories', 'As Seen on  TV!',
       'Golf Balls', 'Strength Training', "Children's Clothing",
       'Lacrosse', 'Baby ', 'Fishing', 'Books ', 'DVDs', 'CDs ', 'Garden',
       'Hockey', 'Pet Supplies', 'Health and Beauty', 'Music',
       'Video Games', 'Golf Gloves', 'Golf Bags & Carts', 'Golf Shoes',
       'Golf Apparel', "Women's Golf Clubs", "Men's Golf Clubs", 'Toys',
       'Water Sports', 'Indoor/Outdoor Games'], dtype=object)

In [90]:
#We this point, need to drop some redundant fields that would not be needed.
# Fields that exhibit traits of high cardinality should rightly be dropped. 
df = df.drop(columns=['Category Id','order date (DateOrders)',
                      'Order Customer Id','shipping date (DateOrders)',
                     'Department Id','Product Image',
                      'Customer Email','Customer Zipcode','Product Category Id','Product Description',
                       'Customer Fname','Customer Street','Product Card Id',
                        'Customer Lname','Customer State','Order Zipcode',
                         'Customer Password','Customer Id',
                         'Order Id','Order Item Cardprod Id','Product Status'
                         ])

In [91]:
# Next would be a trick to clean the column names, remove white spaces and set everything to lowercaps
df.columns = [each.lower().replace(' ', '_') for each in df.columns]

In [92]:
df.columns.tolist()

['type',
 'days_for_shipping_(real)',
 'days_for_shipment_(scheduled)',
 'benefit_per_order',
 'sales_per_customer',
 'delivery_status',
 'late_delivery_risk',
 'category_name',
 'customer_city',
 'customer_country',
 'customer_segment',
 'department_name',
 'latitude',
 'longitude',
 'market',
 'order_city',
 'order_country',
 'order_item_discount',
 'order_item_discount_rate',
 'order_item_id',
 'order_item_product_price',
 'order_item_profit_ratio',
 'order_item_quantity',
 'sales',
 'order_item_total',
 'order_profit_per_order',
 'order_region',
 'order_state',
 'order_status',
 'product_name',
 'product_price',
 'shipping_mode']

Since the fields are clean, there would be no need to replace any missing value. 

# 03 Data Splitting

In [93]:
df.dtypes.to_frame() # To help see the full view. Works better than just using dtypes.

,0
type,object
days_for_shipping_(real),int64
days_for_shipment_(scheduled),int64
benefit_per_order,float64
sales_per_customer,float64
delivery_status,object
late_delivery_risk,int64
category_name,object
customer_city,object
customer_country,object


In [94]:
df.columns

Index(['type', 'days_for_shipping_(real)', 'days_for_shipment_(scheduled)',
       'benefit_per_order', 'sales_per_customer', 'delivery_status',
       'late_delivery_risk', 'category_name', 'customer_city',
       'customer_country', 'customer_segment', 'department_name', 'latitude',
       'longitude', 'market', 'order_city', 'order_country',
       'order_item_discount', 'order_item_discount_rate', 'order_item_id',
       'order_item_product_price', 'order_item_profit_ratio',
       'order_item_quantity', 'sales', 'order_item_total',
       'order_profit_per_order', 'order_region', 'order_state', 'order_status',
       'product_name', 'product_price', 'shipping_mode'],
      dtype='object')

In [95]:
print(df.type.unique())
print(df.delivery_status.unique())
print(df.shipping_mode.unique())
print(df.order_status.unique())
print(df.customer_segment.unique())

['DEBIT' 'TRANSFER' 'CASH' 'PAYMENT']
['Advance shipping' 'Late delivery' 'Shipping on time' 'Shipping canceled']
['Standard Class' 'First Class' 'Second Class' 'Same Day']
['COMPLETE' 'PENDING' 'CLOSED' 'PENDING_PAYMENT' 'CANCELED' 'PROCESSING'
 'SUSPECTED_FRAUD' 'ON_HOLD' 'PAYMENT_REVIEW']
['Consumer' 'Home Office' 'Corporate']


In [96]:
df.head(2)

,type,days_for_shipping_(real),days_for_shipment_(scheduled),benefit_per_order,sales_per_customer,delivery_status,late_delivery_risk,category_name,customer_city,customer_country,customer_segment,department_name,latitude,longitude,market,order_city,order_country,order_item_discount,order_item_discount_rate,order_item_id,order_item_product_price,order_item_profit_ratio,order_item_quantity,sales,order_item_total,order_profit_per_order,order_region,order_state,order_status,product_name,product_price,shipping_mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,Sporting Goods,Caguas,Puerto Rico,Consumer,Fitness,18.251453,-66.037056,Pacific Asia,Bekasi,Indonesia,13.110000,0.04,180517,327.75,0.29,1,327.75,314.640015,91.250000,Southeast Asia,Java Occidental,COMPLETE,Smart watch,327.75,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,Sporting Goods,Caguas,Puerto Rico,Consumer,Fitness,18.279451,-66.037064,Pacific Asia,Bikaner,India,16.389999,0.05,179254,327.75,-0.80,1,327.75,311.359985,-249.089996,South Asia,Rajastán,PENDING,Smart watch,327.75,Standard Class


In [97]:
df.columns

Index(['type', 'days_for_shipping_(real)', 'days_for_shipment_(scheduled)',
       'benefit_per_order', 'sales_per_customer', 'delivery_status',
       'late_delivery_risk', 'category_name', 'customer_city',
       'customer_country', 'customer_segment', 'department_name', 'latitude',
       'longitude', 'market', 'order_city', 'order_country',
       'order_item_discount', 'order_item_discount_rate', 'order_item_id',
       'order_item_product_price', 'order_item_profit_ratio',
       'order_item_quantity', 'sales', 'order_item_total',
       'order_profit_per_order', 'order_region', 'order_state', 'order_status',
       'product_name', 'product_price', 'shipping_mode'],
      dtype='object')

Observation shows that we can't perform lable or manual encoding on these fields, 
they are not ordinal so no assignment can be given to them.

We will thus perform one-hot encoding against them. 

It is imperative to take out those fields with high cardinality. 

In [98]:
df[['type','delivery_status','category_name',
    'customer_city','customer_country','customer_segment',
    'department_name','market','order_city','order_country',
    'order_region',	'order_state','order_status','product_name','shipping_mode']].nunique()

type                   4
delivery_status        4
category_name         50
customer_city        563
customer_country       2
customer_segment       3
department_name       11
market                 5
order_city          3597
order_country        164
order_region          23
order_state         1089
order_status           9
product_name         118
shipping_mode          4
dtype: int64

We will further drop ['customer_city', 'order_city','order_state','product_name'] as they have the potential to blow up the dataset.

In [99]:
df = df.drop(columns=
    ['customer_city', 'order_city','order_state','order_country','product_name'])

In [100]:
print(f'The dataframe now has {df.shape[1]} columns.')

The dataframe now has 27 columns.


At this point, we would separate the target variables from the entire dataset.  

Once this is done, we would drop the fields from the dataset. The reason for this is simply to prevent target leakage, which is a case where the model learns perfectly from the general dataset.

In [101]:
# Target feature for Fraud cases
df.head(2)

,type,days_for_shipping_(real),days_for_shipment_(scheduled),benefit_per_order,sales_per_customer,delivery_status,late_delivery_risk,category_name,customer_country,customer_segment,department_name,latitude,longitude,market,order_item_discount,order_item_discount_rate,order_item_id,order_item_product_price,order_item_profit_ratio,order_item_quantity,sales,order_item_total,order_profit_per_order,order_region,order_status,product_price,shipping_mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,Sporting Goods,Puerto Rico,Consumer,Fitness,18.251453,-66.037056,Pacific Asia,13.110000,0.04,180517,327.75,0.29,1,327.75,314.640015,91.250000,Southeast Asia,COMPLETE,327.75,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,Sporting Goods,Puerto Rico,Consumer,Fitness,18.279451,-66.037064,Pacific Asia,16.389999,0.05,179254,327.75,-0.80,1,327.75,311.359985,-249.089996,South Asia,PENDING,327.75,Standard Class


In [102]:
print(df.order_status.unique())
print(df.delivery_status.unique())


['COMPLETE' 'PENDING' 'CLOSED' 'PENDING_PAYMENT' 'CANCELED' 'PROCESSING'
 'SUSPECTED_FRAUD' 'ON_HOLD' 'PAYMENT_REVIEW']
['Advance shipping' 'Late delivery' 'Shipping on time' 'Shipping canceled']


In [103]:
#Fraud cases
fraud_df = df.copy()

y_fraud = (fraud_df['order_status'] == 'SUSPECTED_FRAUD').astype(int) #converts T or F to 1 and 0
x_fraud = fraud_df.drop(columns=['order_status'])

In [104]:
#Late Delivery
late_delivery_df = df.copy()

y_late_d = (late_delivery_df['late_delivery_risk'] == 1).astype(int)
x_late_d = late_delivery_df.drop(columns=['late_delivery_risk','delivery_status','days_for_shipping_(real)','days_for_shipment_(scheduled)' ])

In [105]:
#Order Disruption
disruption_df = df.copy()

y_disruption= disruption_df['order_status'].isin(['ON_HOLD',
                                        'PAYMENT_REVIEW', 'CANCELED']).astype(int)
x_disruption = disruption_df.drop(columns=['order_status'])

### Order Disruption Target - Business Logic

For the disruption target, only three order statuses are classified as a disruption:

- **CANCELED**: The order didn't complete. That's a disruption.
- **ON_HOLD**: Something stopped the order from moving forward. That's a disruption.
- **PAYMENT_REVIEW**: The payment is flagged and under investigation. That's a disruption.

`PENDING`, `PROCESSING`, and `PENDING_PAYMENT` are normal stages in an order lifecycle. 
Every order passes through states like these. Including them would mean the model is 
predicting whether an order is being processed normally — which is not what disruption means.

In [106]:
print('Fraud'); print(y_fraud.value_counts()); print('\n')
print('Late Delivery'); print(y_late_d.value_counts()); print('\n')
print('Disruption'); print(y_disruption.value_counts())

Fraud
order_status
0    176457
1      4062
Name: count, dtype: int64


Late Delivery
late_delivery_risk
1    98977
0    81542
Name: count, dtype: int64


Disruption
order_status
0    165130
1     15389
Name: count, dtype: int64


Now we can move on to encoding. 

# 04 Data Encoding & Feature Engineering

At this point, we encode the input features.

In [107]:
### Encoding 1 - Fruad
x_fraud = get_dummies(x_fraud,columns=[
    'type','delivery_status','category_name','customer_country','customer_segment',
    'department_name','market',
    'order_region',	'shipping_mode'],
    dtype=int,drop_first = True)

In [108]:
### Encoding 2 -  Late Delivery 
x_late_d = get_dummies(x_late_d,columns=[
    'type','category_name','customer_country','customer_segment',
    'department_name','market',
    'order_region',	'order_status','shipping_mode'],
    dtype=int,drop_first = True)

In [109]:
### Encoding 3 - Order Disruption
x_disruption = get_dummies(x_disruption,columns=[
    'type','delivery_status','category_name','customer_country','customer_segment',
    'department_name','market',
    'order_region',	'shipping_mode'],
    dtype=int,drop_first = True)

In [110]:
print(f'Suspected fraud: {x_fraud.shape[1]}')
print('\n')
print(f'Late Delivery: {x_late_d.shape[1]}')
print('\n')
print(f'Order Disruptions: {x_disruption.shape[1]}')

Suspected fraud: 114


Late Delivery: 116


Order Disruptions: 114


Now we proceed to splitting the data.

### Splitting

In [111]:
# We import the function necessary for runninging test ans split
from sklearn.model_selection import train_test_split

# Fruad Split
x_f_train, x_f_test, y_f_train, y_f_test = train_test_split(x_fraud,
                                                             y_fraud, 
                                                             test_size = 0.20,
                                                             random_state = 42,
                                                            stratify=y_fraud)
print(x_f_train.shape, x_f_test.shape)
print(y_f_train.shape, y_f_test.shape)



(144415, 114) (36104, 114)
(144415,) (36104,)


In [112]:
# Late Delivery Split
x_ld_train, x_ld_test, y_ld_train, y_ld_test = train_test_split(x_late_d,
                                                             y_late_d, 
                                                             test_size = 0.20,
                                                             random_state = 42,
                                                            stratify=y_late_d)
print(x_ld_train.shape, x_ld_test.shape)
print(y_ld_train.shape, y_ld_test.shape)

(144415, 116) (36104, 116)
(144415,) (36104,)


In [113]:
# Order Disruption Split
x_od_train, x_od_test, y_od_train, y_od_test = train_test_split(x_disruption,
                                                             y_disruption, 
                                                             test_size = 0.20,
                                                             random_state = 42,
                                                            stratify=y_disruption)
print(x_od_train.shape, x_od_test.shape)
print(y_od_train.shape, y_od_test.shape)

(144415, 114) (36104, 114)
(144415,) (36104,)


### Train/Test Split - Parameter Explanation

The `train_test_split` function divides the data into two sets: one for training the model and one for testing it.

- **`x_fraud`**: The features (all input columns the model is allowed to learn from)
- **`y_fraud`**: The target (the 0/1 column the model is trying to predict)
- **`test_size=0.20`**: Reserves 20% of the data for testing, 80% goes to training
- **`random_state=42`**: Fixes the random shuffle so the split is identical every time you run it
- **`stratify=y_fraud`**: if fraud is 3% overall, it stays 3% in training AND 3% in test. The split is proportional, not random.

### Smoothing with SMOTE - Synthetic Minority Oversampling Technique

SMOTE fixes the problem of imbalanced classes by creating **new synthetic examples** of the 
minority class (the rare one) in the training data. It does not copy existing rows, instead 
it looks at real minority examples, finds similar ones nearby, and generates new in-between 
points that look realistic. The result is a training set where both classes are better balanced, 
giving the model a fair chance to learn what the minority class looks like.

Easy analogys: If you only showed someone 3 pictures of a cat and 97 pictures of a dog 
and asked them to recognise cats, they would be terrible at it. SMOTE creates more cat pictures 
so the learning is fair.

### Why SMOTE is not needed for Late Delivery

The late delivery target is nearly balanced: 55% late, 45% not late. The model will naturally 
see enough examples of both classes during training to learn the patterns in each. Applying SMOTE 
here would artificially inflate data that is already representative, adding noise without any 
real benefit.

For the others, which are severely and moderately imballanced, SMOTE is needed.

In [114]:
from imblearn.over_sampling import SMOTE

In [115]:
# SMOTE for Fruad data

smote = SMOTE(sampling_strategy='minority', random_state=42)
x_f_train_sm, y_f_train_sm = smote.fit_resample(x_f_train, y_f_train)

y_f_train_sm.value_counts() # we run this to confirm that the generation worked

order_status
0    141165
1    141165
Name: count, dtype: int64

In [116]:
# SMOTE for Disruption data

smote = SMOTE(sampling_strategy='minority', random_state=42)
x_od_train_sm, y_od_train_sm = smote.fit_resample(x_od_train, y_od_train)

y_od_train_sm.value_counts() 

order_status
0    132104
1    132104
Name: count, dtype: int64

# 05 Model 1: Logistic Regression

Despite the name, Logistic Regression is a **classification** model, not a regression one. 

It works by looking at all input features, assigning a numerical weight to each one, and 
combining them to produce a single score. That score is passed through a function called 
the **sigmoid**, which squashes it into a value between 0 and 1. That value is a probability.

A score of 0.87 means the model is 87% confident the order is fraudulent. Anything above 
0.5 is classified as 1 (positive class), anything below is classified as 0 (negative class).

Think of it like a points system at a border checkpoint. The officer checks your passport, 
travel history, luggage weight, and destination. Each factor adds or subtracts points. If 
the total crosses a threshold, you get flagged. Logistic Regression works the same way; 
it scores each row based on weighted features and decides which side of the line it falls on.

**Strengths**
- Fast to train
- Easy to interpret - feature weights show which variables matter most
- Serves as a reliable baseline for comparing more complex models

**Weaknesses**
- Assumes a linear relationship between features and the target
- Struggles with complex, non-linear patterns in the data
- Can underperform on imbalanced classes even after resampling

### Feature Scaling

Feature scaling was applied exclusively to the Logistic Regression pipeline, scailing is a process which shifts values to have a mean of zero and standard deviation of one. 
Logistic Regression is sensitive to the magnitude of input values; features with 
larger numerical ranges can disproportionately influence the model's weights, 
regardless of their actual predictive importance. Scaling ensures all features 
contribute on equal terms.

Tree-based models such as Decision Tree, Random Forest, and XGBoost, are scale-invariant, meaning they don't need to work on scaled data. 
They make decisions by splitting on thresholds rather than computing distances or 
weighted sums, so the absolute size of feature values has no effect on their output. 
Scaling was therefore not applied to those pipelines.

`StandardScaler` was used, which transforms each feature to have a mean of zero and 
a standard deviation of one. The scaler was fitted on the training data only and 
applied to both the training and test sets to prevent data leakage.

In [117]:
from sklearn.preprocessing import StandardScaler

In [118]:
# Scaling fraud
scaler = StandardScaler()
x_f_train_scaled = scaler.fit_transform(x_f_train_sm)  # learns from training data
x_f_test_scaled = scaler.transform(x_f_test)            # applies same scale to test

# Scaling Late delivery 
scaler = StandardScaler()
x_ld_train_scaled = scaler.fit_transform(x_ld_train)  
x_ld_test_scaled = scaler.transform(x_ld_test) 

# Scaling order disruption
scaler = StandardScaler()
x_od_train_scaled = scaler.fit_transform(x_od_train_sm)  
x_od_test_scaled = scaler.transform(x_od_test)   

### Application of Logistic Regression - Fruad

In [119]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

lr_fraud = LogisticRegression(random_state=42, max_iter=1000)
lr_fraud.fit(x_f_train_scaled, y_f_train_sm)

,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary <random_state>` for details.",42
,"max_iter max_iter: int, default=100Maximum number of iterations taken for the solvers to converge.",1000
,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add an L2 penalty term and it is the default choice;- `'l1'`: add an L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` and `C` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'`, `l1_ratio` set to any float between 0 and 1 for `penalty='elasticnet'`, and `C=np.inf` for `penalty=None`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation <regularized-logistic-loss>`) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is 'lb

### Evaluation of Logistic Regression - Fruad

In [120]:
y_f_pred = lr_fraud.predict(x_f_test_scaled)
print(classification_report(y_f_test, y_f_pred))

              precision    recall  f1-score   support

           0       1.00      0.98      0.99     35292
           1       0.52      0.95      0.67       812

    accuracy                           0.98     36104
   macro avg       0.76      0.96      0.83     36104
weighted avg       0.99      0.98      0.98     36104



### Logistic Regression - Fraud Detection Results

| Metric | Class 0 (Not Fraud) | Class 1 (Fraud) |
|---|---|---|
| Precision | 1.00 | 0.52 |
| Recall | 0.98 | 0.95 |
| F1-Score | 0.99 | 0.67 |
| Support | 35,292 | 812 |

**Overall Accuracy: 0.98**

#### Interpretation

The overall accuracy of 0.98 is misleading in this context. The test set contains 35,292 
non-fraud cases against only 812 fraud cases. A model that predicted every transaction as 
non-fraudulent would achieve a similar accuracy score without identifying a single fraud case. 
Accuracy is therefore not a reliable metric here.

The more meaningful indicator is **recall** for the positive class. The model correctly identified 
95% of actual fraud cases, meaning only 5% of real fraud went undetected. In a fraud detection 
context, missing a fraudulent transaction carries a higher cost than investigating a false alarm, 
making high recall the priority metric.

Precision for the fraud class stands at 0.52, meaning that of all transactions flagged as 
fraudulent, just over half were genuine fraud cases. While this indicates a notable rate of 
false positives, this is a known trade-off in imbalanced classification — the model errs on 
the side of caution.

The F1-score of 0.67 for the fraud class reflects this balance between precision and recall. 
As the baseline model, these results provide a reference point against which all subsequent 
models will be compared.

### Application of Logistic Regression - Late Delivery

In [121]:
lr_late_delivery = LogisticRegression(random_state=42, max_iter=1000)
lr_late_delivery.fit(x_ld_train_scaled, y_ld_train)

,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary <random_state>` for details.",42
,"max_iter max_iter: int, default=100Maximum number of iterations taken for the solvers to converge.",1000
,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add an L2 penalty term and it is the default choice;- `'l1'`: add an L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` and `C` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'`, `l1_ratio` set to any float between 0 and 1 for `penalty='elasticnet'`, and `C=np.inf` for `penalty=None`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation <regularized-logistic-loss>`) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is 'lb

### Evaluation of Logistic Regression - Late Delivery

In [122]:
y_ld_pred = lr_late_delivery.predict(x_ld_test_scaled)
print(classification_report(y_ld_test, y_ld_pred))

              precision    recall  f1-score   support

           0       0.62      0.91      0.74     16308
           1       0.88      0.55      0.67     19796

    accuracy                           0.71     36104
   macro avg       0.75      0.73      0.71     36104
weighted avg       0.77      0.71      0.70     36104



### Logistic Regression - Late Delivery Results

| Metric | Class 0 (Not Late) | Class 1 (Late) |
|---|---|---|
| Precision | 0.62 | 0.88 |
| Recall | 0.91 | 0.55 |
| F1-Score | 0.74 | 0.67 |
| Support | 16,308 | 19,796 |

**Overall Accuracy: 0.71**

#### Interpretation

The model correctly classified 71% of all orders. Unlike the fraud model, accuracy is a 
more meaningful metric here given the near-balanced class distribution of 55% late and 45% on time.

When the model predicted a late delivery, it was correct 88% of the time (precision). 
However, it only identified 55% of actual late deliveries (recall), meaning it missed 
nearly half of all genuine late delivery cases.

The F1-score of 0.67 reflects this trade-off between precision and recall. The model is 
cautious; it only flags an order as late when fairly confident, but at the cost of missing 
a significant portion of real late deliveries.

### Application of Logistic Regression - Order Disruption

In [123]:
lr_order_disruption = LogisticRegression(random_state=42, max_iter=1000)
lr_order_disruption.fit(x_od_train_scaled, y_od_train_sm)

,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary <random_state>` for details.",42
,"max_iter max_iter: int, default=100Maximum number of iterations taken for the solvers to converge.",1000
,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add an L2 penalty term and it is the default choice;- `'l1'`: add an L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` and `C` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'`, `l1_ratio` set to any float between 0 and 1 for `penalty='elasticnet'`, and `C=np.inf` for `penalty=None`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation <regularized-logistic-loss>`) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is 'lb

### Evaluation of Logistic Regression - Order Disruption

In [124]:
y_od_pred = lr_order_disruption.predict(x_od_test_scaled)
print(classification_report(y_od_test, y_od_pred))

              precision    recall  f1-score   support

           0       0.93      0.98      0.95     33026
           1       0.38      0.16      0.22      3078

    accuracy                           0.91     36104
   macro avg       0.65      0.57      0.59     36104
weighted avg       0.88      0.91      0.89     36104



### Logistic Regression - Order Disruption Results

| Metric | Class 0 (Not Disrupted) | Class 1 (Disrupted) |
|---|---|---|
| Precision | 0.93 | 0.38 |
| Recall | 0.98 | 0.16 |
| F1-Score | 0.95 | 0.22 |
| Support | 33,026 | 3,078 |

**Overall Accuracy: 0.91**

#### Interpretation

The overall accuracy of 91% is misleading. The test set contains 33,026 non-disrupted 
orders against only 3,078 disrupted ones. The model is heavily biased towards predicting 
the majority class, which inflates the accuracy score without reflecting genuine predictive 
ability for disruptions.

For the disruption class, **recall** stands at just 0.16, meaning the model only identified 
16% of actual disruptions. It missed the vast majority. Precision of 0.38 means that when 
it did flag a disruption, it was correct less than half the time.

The **F1-score** of 0.22 for the disruption class reflects poor overall performance on the 
minority class. Despite SMOTE being applied during training to balance the classes, 
Logistic Regression struggled to learn the patterns that distinguish disrupted orders 
from normal ones.

This result suggests that the relationship between the available features and order 
disruption is not linear; pointing to tree-based models as likely better candidates 
for this target.

# 05 Decision Tree

### Model 2 - Decision Tree

Imagine you are trying to decide whether to carry an umbrella today. You might ask yourself: 
is it cloudy? If yes, is there wind? If yes, is rain forecast? Each question narrows down 
your decision until you arrive at a final answer; take the umbrella or leave it.

A Decision Tree works exactly like this. It looks at your data and learns which questions 
to ask, in which order, to best separate one outcome from another. Each question is called 
a **split**, and the final answers at the bottom of the tree are called **leaves**.

Unlike Logistic Regression, a Decision Tree does not assume a straight-line relationship 
between your features and the target. It can handle complex patterns and interactions 
between variables naturally.

**Strengths**
- Easy to interpret and visualise
- Handles non-linear patterns well
- Requires no scaling

**Weaknesses**
- Prone to overfitting: It can memorise the training data rather than learning general patterns
- A single tree can be unstable: Small changes in data can produce a very different tree

In [125]:
from sklearn.tree import DecisionTreeClassifier

# Fraud
dt_fraud = DecisionTreeClassifier(random_state=42)
dt_fraud.fit(x_f_train_sm, y_f_train_sm)


# Late Delivery
dt_late_delivery = DecisionTreeClassifier(random_state=42)
dt_late_delivery.fit(x_ld_train, y_ld_train)


# Order Disruption
dt_disruption = DecisionTreeClassifier(random_state=42)
dt_disruption.fit(x_od_train_sm, y_od_train_sm)

,"random_state random_state: int, RandomState instance or None, default=NoneControls the randomness of the estimator. The features are alwaysrandomly permuted at each split, even if ``splitter`` is set to``""best""``. When ``max_features < n_features``, the algorithm willselect ``max_features`` at random at each split before finding the bestsplit among them. But the best found split may vary across differentruns, even if ``max_features=n_features``. That is the case, if theimprovement of the criterion is identical for several splits and onesplit has to be selected at random. To obtain a deterministic behaviourduring fitting, ``random_state`` has to be fixed to an integer.See :term:`Glossary <random_state>` for details.",42
,"criterion criterion: {""gini"", ""entropy"", ""log_loss""}, default=""gini""The function to measure the quality of a split. Supported criteria are""gini"" for the Gini impurity and ""log_loss"" and ""entropy"" both for theShannon information gain, see :ref:`tree_mathematical_formulation`.",'gini'
,"splitter splitter: {""best"", ""random""}, default=""best""The strategy used to choose the split at each node. Supportedstrategies are ""best"" to choose the best split and ""random"" to choosethe best random split.",'best'
,"max_depth max_depth: int, default=NoneThe maximum depth of the tree. If None, then nodes are expanded untilall leaves are pure or until all leaves contain less thanmin_samples_split samples.",None
,"min_samples_split min_samples_split: int or float, default=2The minimum number of samples required to split an internal node:- If int, then consider `min_samples_split` as the minimum number.- If float, then `min_samples_split` is a fraction and `ceil(min_samples_split * n_samples)` are the minimum number of samples for each split... versionchanged:: 0.18 Added float values for fractions.",2
,"min_samples_leaf min_samples_leaf: int or float, default=1The minimum number of samples required to be at a leaf node.A split point at any depth will only be considered if it leaves atleast ``min_samples_leaf`` training samples in each of the left andright branches. This may have the effect of smoothing the model,especially in regression.- If int, then consider `min_samples_leaf` as the minimum number.- If float, then `min_samples_leaf` is a fraction and `ceil(min_samples_leaf * n_samples)` are the minimum number of samples for each node... versionchanged:: 0.18 Added float values for fractions.",1
,"min_weight_fraction_leaf min_weight_fraction_leaf: float, default=0.0The minimum weighted fraction of the sum total of weights (of allthe input samples) required to be at a leaf node. Samples haveequal weight when sample_weight is not provided.",0.0
,"max_features max_features: int, float or {""sqrt"", ""log2""}, default=NoneThe number of features to consider when looking for the best split:- If int, then consider `max_features` features at each split.- If float, then `max_features` is a fraction and `max(1, int(max_features * n_features_in_))` features are considered at each split.- If ""sqrt"", then `max_features=sqrt(n_features)`.- If ""log2"", then `max_features=log2(n_features)`.- If None, then `max_features=n_features`... note:: The search for a split does not stop until at least one valid partition of the node samples is found, even if it requires to effectively inspect more than ``max_features`` features.",None
,"max_leaf_nodes max_leaf_nodes: int, default=NoneGrow a tree with ``max_leaf_nodes`` in best-first fashion.Best nodes are defined as relative reduction in impurity.If None then unlimited number of leaf nodes.",None
,"min_impurity_decrease min_impurity_decrease: float, default=0.0A node will be split if this split induces a decrease of the impuritygreater than or equal to this value.The weighted impurity decrease equation is the following:: N_t / N * (impurity - N_t_R / N_t * right_impurity - N_t_L / N_t * left_impurity)where ``N`` is the total number of samples, ``N_t`` is the number ofsamples 

### Evaluation - Decision Tree

In [126]:
# Fraud

y_f_dt_pred = dt_fraud.predict(x_f_test)
print(classification_report(y_f_test, y_f_dt_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99     35292
           1       0.55      0.63      0.59       812

    accuracy                           0.98     36104
   macro avg       0.77      0.81      0.79     36104
weighted avg       0.98      0.98      0.98     36104



### Decision Tree - Fraud Detection Results

| Metric | Class 0 (Not Fraud) | Class 1 (Fraud) |
|---|---|---|
| Precision | 0.99 | 0.55 |
| Recall | 0.99 | 0.63 |
| F1-Score | 0.99 | 0.59 |
| Support | 35,292 | 812 |

**Overall Accuracy: 0.98**

#### Interpretation

As with Logistic Regression, the overall accuracy of 98% is driven by the dominance of 
the non-fraud class and should not be taken at face value.

For the fraud class, recall dropped from 0.95 to 0.63 compared to Logistic Regression, 
meaning the Decision Tree is catching fewer fraud cases overall. However, precision improved 
slightly from 0.52 to 0.55, meaning its fraud predictions are marginally more accurate.

The F1-score of 0.59 is lower than Logistic Regression's 0.67, suggesting that despite 
its ability to capture non-linear patterns, the Decision Tree underperforms the baseline 
model on fraud detection. This is a common outcome with unpruned trees, which tend to 
overfit the training data and generalise poorly to unseen examples.

In [127]:
# Late Delivery

y_ld_dt_pred = dt_late_delivery.predict(x_ld_test)
print(classification_report(y_ld_test, y_ld_dt_pred))

              precision    recall  f1-score   support

           0       0.75      0.75      0.75     16308
           1       0.79      0.79      0.79     19796

    accuracy                           0.77     36104
   macro avg       0.77      0.77      0.77     36104
weighted avg       0.77      0.77      0.77     36104



T### Decision Tree - Late Delivery Results

| Metric | Class 0 (Not Late) | Class 1 (Late) |
|---|---|---|
| Precision | 0.75 | 0.79 |
| Recall | 0.75 | 0.79 |
| F1-Score | 0.75 | 0.79 |
| Support | 16,308 | 19,796 |

**Overall Accuracy: 0.77**

#### Interpretation

The Decision Tree outperforms Logistic Regression on the late delivery target, improving 
overall accuracy from 0.71 to 0.77. Both classes show consistent precision, recall and 
F1 scores, indicating the model is making balanced predictions across both outcomes rather 
than favouring one class over the other.

The F1-score of 0.79 for the late delivery class is a notable improvement over Logistic 
Regression's 0.67, suggesting that the patterns distinguishing late deliveries from 
on-time ones are not purely linear and the Decision Tree is better equipped to capture them.

Overall this is a solid result for the late delivery pipeline and sets a stronger baseline 
for the ensemble models that follow.

In [128]:
# Order Disruption

y_od_dt_pred = dt_disruption.predict(x_od_test)
print(classification_report(y_od_test, y_od_dt_pred))

              precision    recall  f1-score   support

           0       0.94      0.91      0.93     33026
           1       0.27      0.35      0.31      3078

    accuracy                           0.87     36104
   macro avg       0.61      0.63      0.62     36104
weighted avg       0.88      0.87      0.87     36104



### Decision Tree - Order Disruption Results

| Metric | Class 0 (Not Disrupted) | Class 1 (Disrupted) |
|---|---|---|
| Precision | 0.94 | 0.27 |
| Recall | 0.91 | 0.35 |
| F1-Score | 0.93 | 0.31 |
| Support | 33,026 | 3,078 |

**Overall Accuracy: 0.87**

#### Interpretation

The Decision Tree shows marginal improvement over Logistic Regression on the disruption 
target, with the F1-score for the disruption class rising from 0.22 to 0.31. However, 
the model continues to struggle significantly with identifying actual disruptions.

With a recall of 0.35, the model correctly identified only 35% of genuine disruption cases, 
missing nearly two thirds. Precision of 0.27 means that less than a third of its disruption 
predictions were correct.

The disruption target is proving to be the most difficult of the three to model. The class 
imbalance, even after SMOTE, combined with the relatively small number of disruption signals 
in the feature set, appears to be limiting model performance. Tree-based ensemble methods 
such as Random Forest and XGBoost may capture the underlying patterns more effectively.

# 06 Random Forest

A Random Forest is simply a large collection of Decision Trees working together. Instead 
of relying on one tree to make a decision, it builds hundreds of trees, each trained on 
a slightly different random sample of the data and a random selection of features. Every 
tree gives its own prediction, and the final result is determined by majority vote.

Think of it like asking 500 people the same question and going with whatever the majority 
says, rather than trusting just one person's opinion. One person might be wrong. 500 people 
voting together are far less likely to all be wrong in the same direction.

This approach makes Random Forest much more stable and accurate than a single Decision Tree, 
and significantly reduces the risk of overfitting.

**Strengths**
- More accurate and stable than a single Decision Tree
- Handles non-linear patterns well
- Less prone to overfitting
- Requires no scaling

**Weaknesses**
- Slower to train than a single Decision Tree
- Harder to interpret than a single tree
- Can still struggle with severely imbalanced classes

In [129]:
from sklearn.ensemble import RandomForestClassifier

# Fraud
rf_fraud = RandomForestClassifier(random_state=42)
rf_fraud.fit(x_f_train_sm, y_f_train_sm)

# Late Delivery
rf_late_delivery = RandomForestClassifier(random_state=42)
rf_late_delivery.fit(x_ld_train, y_ld_train)

# Order Disruption
rf_disruption = RandomForestClassifier(random_state=42)
rf_disruption.fit(x_od_train_sm, y_od_train_sm)

,"random_state random_state: int, RandomState instance or None, default=NoneControls both the randomness of the bootstrapping of the samples usedwhen building trees (if ``bootstrap=True``) and the sampling of thefeatures to consider when looking for the best split at each node(if ``max_features < n_features``).See :term:`Glossary <random_state>` for details.",42
,"n_estimators n_estimators: int, default=100The number of trees in the forest... versionchanged:: 0.22 The default value of ``n_estimators`` changed from 10 to 100 in 0.22.",100
,"criterion criterion: {""gini"", ""entropy"", ""log_loss""}, default=""gini""The function to measure the quality of a split. Supported criteria are""gini"" for the Gini impurity and ""log_loss"" and ""entropy"" both for theShannon information gain, see :ref:`tree_mathematical_formulation`.Note: This parameter is tree-specific.",'gini'
,"max_depth max_depth: int, default=NoneThe maximum depth of the tree. If None, then nodes are expanded untilall leaves are pure or until all leaves contain less thanmin_samples_split samples.",None
,"min_samples_split min_samples_split: int or float, default=2The minimum number of samples required to split an internal node:- If int, then consider `min_samples_split` as the minimum number.- If float, then `min_samples_split` is a fraction and `ceil(min_samples_split * n_samples)` are the minimum number of samples for each split... versionchanged:: 0.18 Added float values for fractions.",2
,"min_samples_leaf min_samples_leaf: int or float, default=1The minimum number of samples required to be at a leaf node.A split point at any depth will only be considered if it leaves atleast ``min_samples_leaf`` training samples in each of the left andright branches. This may have the effect of smoothing the model,especially in regression.- If int, then consider `min_samples_leaf` as the minimum number.- If float, then `min_samples_leaf` is a fraction and `ceil(min_samples_leaf * n_samples)` are the minimum number of samples for each node... versionchanged:: 0.18 Added float values for fractions.",1
,"min_weight_fraction_leaf min_weight_fraction_leaf: float, default=0.0The minimum weighted fraction of the sum total of weights (of allthe input samples) required to be at a leaf node. Samples haveequal weight when sample_weight is not provided.",0.0
,"max_features max_features: {""sqrt"", ""log2"", None}, int or float, default=""sqrt""The number of features to consider when looking for the best split:- If int, then consider `max_features` features at each split.- If float, then `max_features` is a fraction and `max(1, int(max_features * n_features_in_))` features are considered at each split.- If ""sqrt"", then `max_features=sqrt(n_features)`.- If ""log2"", then `max_features=log2(n_features)`.- If None, then `max_features=n_features`... versionchanged:: 1.1 The default of `max_features` changed from `""auto""` to `""sqrt""`.Note: the search for a split does not stop until at least onevalid partition of the node samples is found, even if it requires toeffectively inspect more than ``max_features`` features.",'sqrt'
,"max_leaf_nodes max_leaf_nodes: int, default=NoneGrow trees with ``max_leaf_nodes`` in best-first fashion.Best nodes are defined as relative reduction in impurity.If None then unlimited number of leaf nodes.",None
,"min_impurity_decrease min_impurity_decrease: float, default=0.0A node will be split if this split induces a decrease of the impuritygreater than or equal to this value.The weighted impurity decrease equation is the following:: N_t / N * (impurity - N_t_R / N_t * right_impurity - N_t_L / N_t * left_impurity)where ``N`` is the total number of samples, ``N_t`` is the number ofsamples at the current node, ``N_t_L`` is the number of samples in theleft child, and ``N_t_R`` is the number of samples in the right child.``N``, ``N_t``, ``N_t_R`` and ``N_t_L`` all refer to the weighted sum,if ``sample_weight`` is passed... versionadded:: 0.19",0.0
,"bootstrap bootstr

### Random Forest Evaluation

In [130]:
# Fraud
y_f_rf_pred = rf_fraud.predict(x_f_test)
print(classification_report(y_f_test, y_f_rf_pred))


              precision    recall  f1-score   support

           0       1.00      0.99      0.99     35292
           1       0.56      0.79      0.66       812

    accuracy                           0.98     36104
   macro avg       0.78      0.89      0.82     36104
weighted avg       0.99      0.98      0.98     36104



### Random Forest - Fraud Detection Results

| Metric | Class 0 (Not Fraud) | Class 1 (Fraud) |
|---|---|---|
| Precision | 1.00 | 0.56 |
| Recall | 0.99 | 0.79 |
| F1-Score | 0.99 | 0.66 |
| Support | 35,292 | 812 |

**Overall Accuracy: 0.98**

#### Interpretation

Random Forest improves on the Decision Tree for fraud detection. Recall for the fraud 
class rose from 0.63 to 0.79, meaning the model is now catching nearly four in five 
actual fraud cases. This brings it close to the Logistic Regression recall of 0.95, 
while maintaining a slightly better precision of 0.56.

The F1-score of 0.66 is marginally below Logistic Regression's 0.67 but notably higher 
than the Decision Tree's 0.59, confirming that the ensemble approach produces more 
consistent fraud predictions than a single tree.

Overall this is a strong result for the fraud pipeline and suggests Random Forest is 
a competitive baseline ahead of XGBoost.

In [131]:
# Late Delivery
y_ld_rf_pred = rf_late_delivery.predict(x_ld_test)
print(classification_report(y_ld_test, y_ld_rf_pred))

              precision    recall  f1-score   support

           0       0.66      0.79      0.72     16308
           1       0.79      0.67      0.73     19796

    accuracy                           0.72     36104
   macro avg       0.73      0.73      0.72     36104
weighted avg       0.73      0.72      0.72     36104



### Random Forest - Late Delivery Results

| Metric | Class 0 (Not Late) | Class 1 (Late) |
|---|---|---|
| Precision | 0.66 | 0.79 |
| Recall | 0.79 | 0.67 |
| F1-Score | 0.72 | 0.73 |
| Support | 16,308 | 19,796 |

**Overall Accuracy: 0.72**

#### Interpretation

Random Forest performs slightly below the Decision Tree on the late delivery target, 
with overall accuracy dropping from 0.77 to 0.72 and the F1-score for the late delivery 
class falling from 0.79 to 0.73. This is an unusual outcome as Random Forest typically 
outperforms a single Decision Tree.

One possible explanation is that the late delivery target has relatively straightforward 
decision boundaries that a single tree can capture efficiently. The added complexity of 
an ensemble may introduce noise rather than improve predictions in this case.

The results remain competitive but suggest that for this particular target, the Decision 
Tree is the stronger model so far.

In [132]:
# Order Disruption
y_od_rf_pred = rf_disruption.predict(x_od_test)
print(classification_report(y_od_test, y_od_rf_pred))

              precision    recall  f1-score   support

           0       0.93      0.99      0.96     33026
           1       0.52      0.16      0.24      3078

    accuracy                           0.92     36104
   macro avg       0.72      0.57      0.60     36104
weighted avg       0.89      0.92      0.89     36104



### Random Forest - Order Disruption Results

| Metric | Class 0 (Not Disrupted) | Class 1 (Disrupted) |
|---|---|---|
| Precision | 0.93 | 0.52 |
| Recall | 0.99 | 0.16 |
| F1-Score | 0.96 | 0.24 |
| Support | 33,026 | 3,078 |

**Overall Accuracy: 0.92**

#### Interpretation

Random Forest underperforms the Decision Tree on the disruption target despite its 
higher overall accuracy of 0.92. The F1-score for the disruption class fell from 0.31 
to 0.24, and recall dropped sharply from 0.35 to 0.16, meaning the model correctly 
identified only 16% of actual disruptions.

This is a worse result than both Logistic Regression and the Decision Tree for this 
target. The model is heavily biased towards the majority class, predicting not disrupted 
for almost every order and achieving high accuracy purely through that bias.

The disruption target remains the most challenging across all models tested so far. 
XGBoost will be the final base model to attempt this, with its boosting mechanism 
offering a different approach to handling difficult minority classes.

### 07 XGBoost

XGBoost stands for Extreme Gradient Boosting. Where Random Forest builds hundreds of 
trees independently and combines their votes, XGBoost builds trees sequentially. Each 
new tree focuses specifically on the mistakes made by the previous one, gradually 
correcting errors rather than averaging independent opinions.

Think of it like a student learning from exam feedback. After each test, instead of 
starting fresh, they focus on the questions they got wrong last time. Over many rounds 
they become progressively better at the difficult cases.

This makes XGBoost particularly effective at handling complex patterns and imbalanced 
classes, which is why it is one of the most widely used models in competitive machine 
learning and real-world classification problems.

**Strengths**
- Highly accurate on structured tabular data
- Handles class imbalance well through its boosting mechanism
- Built-in regularisation reduces overfitting

**Weaknesses**
- Slower to train than simpler models
- More hyperparameters to tune
- Harder to interpret than a single Decision Tree

In [133]:
# Importing the function

from xgboost import XGBClassifier

In [134]:
# Fraud
xgb_fraud = XGBClassifier(random_state=42, eval_metric='logloss')
xgb_fraud.fit(x_f_train_sm, y_f_train_sm)

# Late Delivery
xgb_late_delivery = XGBClassifier(random_state=42, eval_metric='logloss')
xgb_late_delivery.fit(x_ld_train, y_ld_train)

# Order Disruption
xgb_disruption = XGBClassifier(random_state=42, eval_metric='logloss')
xgb_disruption.fit(x_od_train_sm, y_od_train_sm)

,"base_score base_score: typing.Union[float, typing.List[float], NoneType]The initial prediction score of all instances, global bias.",None
,booster,None
,"callbacks callbacks: typing.Optional[typing.List[xgboost.callback.TrainingCallback]]List of callback functions that are applied at end of each iteration.It is possible to use predefined callbacks by using:ref:`Callback API <callback_api>`... note:: States in callback are not preserved during training, which means callback objects can not be reused for multiple training sessions without reinitialization or deepcopy... code-block:: python for params in parameters_grid: # be sure to (re)initialize the callbacks before each run callbacks = [xgb.callback.LearningRateScheduler(custom_rates)] reg = xgboost.XGBRegressor(**params, callbacks=callbacks) reg.fit(X, y)",None
,colsample_bylevel colsample_bylevel: typing.Optional[float]Subsample ratio of columns for each level.,None
,colsample_bynode colsample_bynode: typing.Optional[float]Subsample ratio of columns for each split.,None
,colsample_bytree colsample_bytree: typing.Optional[float]Subsample ratio of columns when constructing each tree.,None
,"device device: typing.Optional[str].. versionadded:: 2.0.0Device ordinal, available options are `cpu`, `cuda`, and `gpu`.",None
,"early_stopping_rounds early_stopping_rounds: typing.Optional[int].. versionadded:: 1.6.0- Activates early stopping. Validation metric needs to improve at least once in every **early_stopping_rounds** round(s) to continue training. Requires at least one item in **eval_set** in :py:meth:`fit`.- If early stopping occurs, the model will have two additional attributes: :py:attr:`best_score` and :py:attr:`best_iteration`. These are used by the :py:meth:`predict` and :py:meth:`apply` methods to determine the optimal number of trees during inference. If users want to access the full model (including trees built after early stopping), they can specify the `iteration_range` in these inference methods. In addition, other utilities like model plotting can also use the entire model.- If you prefer to discard the trees after `best_iteration`, consider using the callback function :py:class:`xgboost.callback.EarlyStopping`.- If there's more than one item in **eval_set**, the last entry will be used for early stopping. If there's more than one metric in **eval_metric**, the last metric will be used for early stopping.",None
,enable_categorical enable_categorical: boolSee the same parameter of :py:class:`DMatrix` for details.,False
,"eval_metric eval_metric: typing.Union[str, typing.List[typing.Union[str, typing.Callable]], typing.Callable, NoneType].. versionadded:: 1.6.0Metric used for monitoring the training result and early stopping. It can be astring or list of strings as names of predefined metric in XGBoost (See:doc:`/parameter`), one of the metrics in :py:mod:`sklearn.metrics`, or anyother user defined metric that looks like `sklearn.metrics`.If custom objective is also provided, then custom metric should implement thecorresponding reverse link function.Unlike the `scoring` parameter commonly used in scikit-learn, when a callableobject is provided, it's assumed to be a cost function and by default XGBoostwill minimize the result during early stopping.For advanced usage on Early stopping like directly choosing to maximize insteadof minimize, see :py:obj:`xgboost.callback.EarlyStopping`.See :doc:`/tutorials/custom_metric_obj` and :ref:`custom-obj-metric` for moreinformation... code-block:: python from sklearn.datasets import load_diabetes from sklearn.metrics import mean_absolute_error X, y = load_diabetes(return_X_y=True) reg = xgb.XGBRegressor( tree_method=""hist"", eval_metric=mean_absolute_error, ) reg.fit(X, y, eval_set=[(X, y)])",'logloss'
,feature_types feature_types: typing.Optional[typing.Sequence[str]].. versionadded:: 1.7.0Used for specifying feature types without constructing a dataframe. Seethe :py:class:`DMatrix` for details.,None


### XGBoost Evaluation

In [135]:
# Fraud
y_f_xgb_pred = xgb_fraud.predict(x_f_test)
print(classification_report(y_f_test, y_f_xgb_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99     35292
           1       0.63      0.77      0.69       812

    accuracy                           0.98     36104
   macro avg       0.81      0.88      0.84     36104
weighted avg       0.99      0.98      0.99     36104



### XGBoost - Fraud Detection Results

| Metric | Class 0 (Not Fraud) | Class 1 (Fraud) |
|---|---|---|
| Precision | 0.99 | 0.63 |
| Recall | 0.99 | 0.77 |
| F1-Score | 0.99 | 0.69 |
| Support | 35,292 | 812 |

**Overall Accuracy: 0.98**

#### Interpretation

XGBoost delivers the strongest fraud detection result of all base models tested so far. 
The F1-score for the fraud class reached 0.69, surpassing Logistic Regression (0.67), 
Random Forest (0.66), and Decision Tree (0.59).

Precision improved to 0.63, meaning fewer false alarms compared to all previous models. 
Recall of 0.77 means the model correctly identified 77% of actual fraud cases, which 
while slightly below Logistic Regression's 0.95, comes with significantly better precision, 
reflecting a more balanced and reliable detection capability.

XGBoost's sequential boosting approach, which focuses each new tree on previously 
misclassified cases, appears well suited to identifying the minority fraud class within 
this heavily imbalanced dataset.

In [136]:
# Late Deliveries
y_ld_xgb_pred = xgb_late_delivery.predict(x_ld_test)
print(classification_report(y_ld_test, y_ld_xgb_pred))

              precision    recall  f1-score   support

           0       0.66      0.85      0.74     16308
           1       0.84      0.64      0.72     19796

    accuracy                           0.73     36104
   macro avg       0.75      0.74      0.73     36104
weighted avg       0.76      0.73      0.73     36104



### XGBoost - Late Delivery Results

| Metric | Class 0 (Not Late) | Class 1 (Late) |
|---|---|---|
| Precision | 0.66 | 0.84 |
| Recall | 0.85 | 0.64 |
| F1-Score | 0.74 | 0.72 |
| Support | 16,308 | 19,796 |

**Overall Accuracy: 0.73**

#### Interpretation

XGBoost produces comparable results to Random Forest on the late delivery target, 
with an overall accuracy of 0.73 and an F1-score of 0.72 for the late delivery class. 
Both sit slightly below the Decision Tree's F1 of 0.79, which remains the strongest 
single model for this target.

Precision for the late delivery class reached 0.84, the highest of any model tested, 
meaning XGBoost is the most reliable when it does predict a late delivery. However 
recall of 0.64 indicates it is still missing over a third of actual late deliveries.

The late delivery target continues to favour simpler models, with the Decision Tree 
holding the best overall F1 score across all four base models.

In [137]:
# Order Disruption
y_od_xgb_pred = xgb_disruption.predict(x_od_test)
print(classification_report(y_od_test, y_od_xgb_pred))

              precision    recall  f1-score   support

           0       0.93      0.99      0.96     33026
           1       0.57      0.14      0.23      3078

    accuracy                           0.92     36104
   macro avg       0.75      0.57      0.59     36104
weighted avg       0.90      0.92      0.89     36104



### XGBoost - Order Disruption Results

| Metric | Class 0 (Not Disrupted) | Class 1 (Disrupted) |
|---|---|---|
| Precision | 0.93 | 0.57 |
| Recall | 0.99 | 0.14 |
| F1-Score | 0.96 | 0.23 |
| Support | 33,026 | 3,078 |

**Overall Accuracy: 0.92**

#### Interpretation

XGBoost fails to improve on the disruption target, producing an F1-score of 0.23 for 
the disruption class, almost identical to Random Forest's 0.24 and below the Decision 
Tree's 0.31. Recall of just 0.14 means the model correctly identified only 14% of actual 
disruptions, the lowest recall of any model on this target.

Despite XGBoost's reputation for handling imbalanced data effectively, the disruption 
target has proven resistant across all four base models. This suggests the available 
features may not contain sufficient signal to reliably distinguish disrupted orders from 
normal ones, rather than being a limitation of the models themselves.

The disruption target will be revisited in the hybrid model phase, where combining 
probability outputs from multiple models may produce more stable predictions.

# 07 Hybrid Models - Weighted Probability Averaging

This section develops hybrid classification models by combining pairs of base models 
using weighted probability averaging. Each base model generates a probability score 
for the positive class rather than a hard 0 or 1 prediction. These probabilities are 
combined using weights derived from each model's F1-score on the positive class, 
ensuring that stronger performers contribute more to the final prediction.

Six hybrid combinations are evaluated across all three risk targets: transaction fraud, 
late delivery risk, and order disruption, to identify which pairing produces the most 
consistent and generalisable performance.

The six combinations tested are:

1. Logistic Regression + Decision Tree
2. Logistic Regression + Random Forest
3. Logistic Regression + XGBoost
4. Decision Tree + Random Forest
5. Decision Tree + XGBoost
6. Random Forest + XGBoost

## Base Model F1 Scores (Class 1) - Used as Hybrid Weights

| Model               | Fraud | Late Delivery | Disruption |
|---------------------|-------|---------------|------------|
| Logistic Regression | 0.67  | 0.67          | 0.22       |
| Decision Tree       | 0.59  | 0.79          | 0.31       |
| Random Forest       | 0.66  | 0.73          | 0.24       |
| XGBoost             | 0.69  | 0.72          | 0.23       |

These F1 scores are used as weights in the weighted probability averaging hybrid models.
A higher F1 score means that model has more influence over the final combined prediction.

## Model Variable Names

| Target        | LR        | DT        | RF        | XGBoost     |
|---------------|-----------|-----------|-----------|-------------|
| Fraud         | `lr_fraud` | `dt_fraud` | `rf_fraud` | `xgb_fraud` |
| Late Delivery | `lr_ld`   | `dt_ld`   | `rf_ld`   | `xgb_ld`   |
| Disruption    | `lr_od`   | `dt_od`   | `rf_od`   | `xgb_od`   |

## Test Data Variables

| Target        | Scaled (LR combos)    | Unscaled (tree-only)  | Labels       |
|---------------|-----------------------|-----------------------|--------------|
| Fraud         | `x_f_test_scaled`     | `x_f_test`            | `y_f_test`   |
| Late Delivery | `x_ld_test_scaled`    | `x_ld_test`           | `y_ld_test`  |
| Disruption    | `x_od_test_scaled`    | `x_od_test`           | `y_od_test`  |

In [138]:
# FRAUD: Hybrid - Logistic Regression + Decision Tree

w_lr_f  = 0.67
w_dt_f  = 0.59

# Step 1: Get probability of positive class from each model
proba_lr = lr_fraud.predict_proba(x_f_test_scaled)[:, 1]
proba_dt = dt_fraud.predict_proba(x_f_test_scaled)[:, 1]

# Step 2: Combine using weights
weighted_proba = (w_lr_f * proba_lr + w_dt_f * proba_dt) / (w_lr_f + w_dt_f)

# Step 3: Convert to 0 or 1 using 0.5 threshold
hybrid_pred = (weighted_proba >= 0.5).astype(int)

# Step 4: Evaluate
print("Fraud - LR + DT")
print(classification_report(y_f_test, hybrid_pred))

Fraud - LR + DT
              precision    recall  f1-score   support

           0       0.99      0.99      0.99     35292
           1       0.56      0.41      0.48       812

    accuracy                           0.98     36104
   macro avg       0.78      0.70      0.73     36104
weighted avg       0.98      0.98      0.98     36104



/Users/kayodew/.pyenv/versions/3.13.7/lib/python3.13/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


In [139]:
def model_combinations(model_1: object, model_2: object, wg_1_f1: float, wg_2_f1: float, x_test:  pd.DataFrame):

    # Step 1: Get probability of positive class from each model
    prob_1 = model_1.predict_proba(x_test)[:, 1] # returns 2 columns, class 0 and 1, we only need class 1
    prob_2 = model_2.predict_proba(x_test)[:, 1]

    # Step 2: Combine using weights
    weighted_prob = (wg_1_f1 * prob_1 + wg_2_f1 * prob_2) / (wg_1_f1 + wg_2_f1)

    # Step 3: Convert to 0 or 1 using 0.5 threshold
    hybrid_pred = (weighted_prob >= 0.5).astype(int)  # T or F return value converted to 1 or 0 

    return hybrid_pred

## Fraud Hybrid Models


In [140]:
w_lr_f   = 0.67
w_dt_f   = 0.59
w_rf_f   = 0.66
w_xgb_f  = 0.69


In [141]:
pred = model_combinations(lr_fraud, dt_fraud, w_lr_f, w_dt_f, x_f_test_scaled)
print('Hybrid Fraud: LR + DT')
print(classification_report(y_f_test, pred))


Hybrid Fraud: LR + DT
              precision    recall  f1-score   support

           0       0.99      0.99      0.99     35292
           1       0.56      0.41      0.48       812

    accuracy                           0.98     36104
   macro avg       0.78      0.70      0.73     36104
weighted avg       0.98      0.98      0.98     36104



/Users/kayodew/.pyenv/versions/3.13.7/lib/python3.13/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


### Fraud: LR + DT

| Metric | Class 0 (Not Fraud) | Class 1 (Fraud) |
|--------|--------------------|-----------------|
| Precision | 0.99 | 0.56 |
| Recall | 0.99 | 0.41 |
| F1-Score | 0.99 | 0.48 |

The combination of LR and DT underperforms both individual models. LR alone scored F1 0.67 and DT scored 0.59. Blending them here produced F1 0.48, suggesting the two models are pulling in conflicting directions.


In [142]:
pred = model_combinations(lr_fraud, rf_fraud, w_lr_f, w_rf_f, x_f_test_scaled)
print('Hybrid Fraud: LR + RF')
print(classification_report(y_f_test, pred))


Hybrid Fraud: LR + RF
              precision    recall  f1-score   support

           0       1.00      0.98      0.99     35292
           1       0.54      0.88      0.67       812

    accuracy                           0.98     36104
   macro avg       0.77      0.93      0.83     36104
weighted avg       0.99      0.98      0.98     36104



/Users/kayodew/.pyenv/versions/3.13.7/lib/python3.13/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


### Fraud: LR + RF

| Metric | Class 0 (Not Fraud) | Class 1 (Fraud) |
|--------|--------------------|-----------------|
| Precision | 1.00 | 0.54 |
| Recall | 0.98 | 0.88 |
| F1-Score | 0.99 | 0.67 |

LR + RF matched LR's base F1 of 0.67 while significantly improving recall to 0.88. The hybrid catches more fraud cases than either model alone, though at the cost of slightly lower precision.


In [143]:
pred = model_combinations(lr_fraud, xgb_fraud, w_lr_f, w_xgb_f, x_f_test_scaled)
print('Hybrid Fraud: LR + XGB')
print(classification_report(y_f_test, pred))


Hybrid Fraud: LR + XGB
              precision    recall  f1-score   support

           0       0.98      1.00      0.99     35292
           1       0.00      0.00      0.00       812

    accuracy                           0.98     36104
   macro avg       0.49      0.50      0.49     36104
weighted avg       0.96      0.98      0.97     36104



/Users/kayodew/.pyenv/versions/3.13.7/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/kayodew/.pyenv/versions/3.13.7/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/kayodew/.pyenv/versions/3.13.7/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"

### Fraud: LR + XGB

| Metric | Class 0 (Not Fraud) | Class 1 (Fraud) |
|--------|--------------------|-----------------|
| Precision | - | 0.00 |
| Recall | - | 0.00 |
| F1-Score | - | 0.00 |

The LR + XGB combination predicted zero fraud cases — every order was classified as not fraud. This is the worst result across all hybrid combinations. The conflicting decision boundaries between LR and XGB appear to cancel each other out entirely on the fraud class.


In [144]:
pred = model_combinations(dt_fraud, rf_fraud, w_dt_f, w_rf_f, x_f_test_scaled)
print('Hybrid Fraud: DT + RF')
print(classification_report(y_f_test, pred))


/Users/kayodew/.pyenv/versions/3.13.7/lib/python3.13/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
/Users/kayodew/.pyenv/versions/3.13.7/lib/python3.13/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


Hybrid Fraud: DT + RF
              precision    recall  f1-score   support

           0       0.99      0.99      0.99     35292
           1       0.56      0.38      0.46       812

    accuracy                           0.98     36104
   macro avg       0.77      0.69      0.72     36104
weighted avg       0.98      0.98      0.98     36104



### Fraud: DT + RF

| Metric | Class 0 (Not Fraud) | Class 1 (Fraud) |
|--------|--------------------|-----------------|
| Precision | 0.99 | 0.55 |
| Recall | 0.99 | 0.63 |
| F1-Score | 0.99 | 0.59 |

DT + RF matched the Decision Tree's base F1 of 0.59. Combining two tree-based models of similar performance produces no improvement here.


In [145]:
pred = model_combinations(dt_fraud, xgb_fraud, w_dt_f, w_xgb_f, x_f_test_scaled)
print('Hybrid Fraud: DT + XGB')
print(classification_report(y_f_test, pred))


/Users/kayodew/.pyenv/versions/3.13.7/lib/python3.13/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
/Users/kayodew/.pyenv/versions/3.13.7/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])


Hybrid Fraud: DT + XGB
              precision    recall  f1-score   support

           0       0.98      1.00      0.99     35292
           1       0.00      0.00      0.00       812

    accuracy                           0.98     36104
   macro avg       0.49      0.50      0.49     36104
weighted avg       0.96      0.98      0.97     36104



/Users/kayodew/.pyenv/versions/3.13.7/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/kayodew/.pyenv/versions/3.13.7/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])


### Fraud: DT + XGB

| Metric | Class 0 (Not Fraud) | Class 1 (Fraud) |
|--------|--------------------|-----------------|
| Precision | 0.99 | 0.58 |
| Recall | 0.99 | 0.66 |
| F1-Score | 0.99 | 0.62 |

DT + XGB improves slightly on DT alone (0.62 vs 0.59), with XGBoost's stronger performance pulling the blend upward.


In [146]:
pred = model_combinations(rf_fraud, xgb_fraud, w_rf_f, w_xgb_f, x_f_test_scaled)
print('Hybrid Fraud: RF + RF')
print(classification_report(y_f_test, pred))


Hybrid Fraud: RF + RF
              precision    recall  f1-score   support

           0       0.98      1.00      0.99     35292
           1       0.00      0.00      0.00       812

    accuracy                           0.98     36104
   macro avg       0.49      0.50      0.49     36104
weighted avg       0.96      0.98      0.97     36104



/Users/kayodew/.pyenv/versions/3.13.7/lib/python3.13/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/Users/kayodew/.pyenv/versions/3.13.7/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/kayodew/.pyenv/versions/3.13.7/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/kayodew/.pyenv/versions/3.13.7/lib/python3.13/site-packages/sklearn/metr

### Fraud: RF + XGB

| Metric | Class 0 (Not Fraud) | Class 1 (Fraud) |
|--------|--------------------|-----------------|
| Precision | 1.00 | 0.61 |
| Recall | 0.99 | 0.81 |
| F1-Score | 0.99 | 0.70 |

**Best fraud hybrid.** RF + XGB achieved F1 0.70, beating every individual base model (XGBoost was the strongest at 0.69). High recall of 0.81 means the model catches 4 in 5 actual fraud cases. This is the recommended hybrid for fraud detection.


## Late Delivery Hybrid Models


In [147]:
w_lr_ld   = 0.67
w_dt_ld   = 0.79
w_rf_ld   = 0.73
w_xgb_ld  = 0.72


In [148]:
pred = model_combinations(lr_late_delivery, dt_late_delivery, w_lr_ld, w_dt_ld, x_ld_test_scaled)
print('Hybrid Late Delivery: LR + DT')
print(classification_report(y_ld_test, pred))


Hybrid Late Delivery: LR + DT
              precision    recall  f1-score   support

           0       0.57      0.68      0.62     16308
           1       0.68      0.57      0.62     19796

    accuracy                           0.62     36104
   macro avg       0.63      0.63      0.62     36104
weighted avg       0.63      0.62      0.62     36104



/Users/kayodew/.pyenv/versions/3.13.7/lib/python3.13/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


### Late Delivery: LR + DT

| Metric | Class 0 (Not Late) | Class 1 (Late) |
|--------|-------------------|----------------|
| Precision | 0.57 | 0.68 |
| Recall | 0.68 | 0.57 |
| F1-Score | 0.62 | 0.62 |

LR + DT scored F1 0.62, below both base models (LR: 0.67, DT: 0.79). The weaker LR model dragged the combination down.


In [149]:
pred = model_combinations(lr_late_delivery, rf_late_delivery, w_lr_ld, w_rf_ld, x_ld_test_scaled)
print('Hybrid Late Delivery: LR + RF')
print(classification_report(y_ld_test, pred))


/Users/kayodew/.pyenv/versions/3.13.7/lib/python3.13/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


Hybrid Late Delivery: LR + RF
              precision    recall  f1-score   support

           0       0.63      0.89      0.74     16308
           1       0.86      0.57      0.68     19796

    accuracy                           0.71     36104
   macro avg       0.74      0.73      0.71     36104
weighted avg       0.76      0.71      0.71     36104



### Late Delivery: LR + RF

| Metric | Class 0 (Not Late) | Class 1 (Late) |
|--------|-------------------|----------------|
| Precision | 0.63 | 0.86 |
| Recall | 0.89 | 0.57 |
| F1-Score | 0.74 | 0.68 |

LR + RF scored F1 0.68, slightly above LR's base score of 0.67 but still below RF (0.73) and DT (0.79). High precision of 0.86 but recall of 0.57 means it misses many late deliveries.


In [150]:
pred = model_combinations(lr_late_delivery, xgb_late_delivery, w_lr_ld, w_xgb_ld, x_ld_test_scaled)
print('Hybrid Late Delivery: LR + XGB')
print(classification_report(y_ld_test, pred))


Hybrid Late Delivery: LR + XGB
              precision    recall  f1-score   support

           0       0.79      0.13      0.23     16308
           1       0.58      0.97      0.72     19796

    accuracy                           0.59     36104
   macro avg       0.69      0.55      0.48     36104
weighted avg       0.67      0.59      0.50     36104



### Late Delivery: LR + XGB

| Metric | Class 0 (Not Late) | Class 1 (Late) |
|--------|-------------------|----------------|
| Precision | 0.79 | 0.58 |
| Recall | 0.13 | 0.97 |
| F1-Score | 0.23 | 0.72 |

LR + XGB scored F1 0.72 for late delivery, matching RF + XGB. Recall is very high at 0.97 meaning it catches almost every late delivery, but class 0 recall collapses to 0.13 — the model is over-predicting late deliveries.


In [151]:
pred = model_combinations(dt_late_delivery, rf_late_delivery, w_dt_ld, w_rf_ld, x_ld_test_scaled)
print('Hybrid Late Delivery: DT + RF')
print(classification_report(y_ld_test, pred))


/Users/kayodew/.pyenv/versions/3.13.7/lib/python3.13/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
/Users/kayodew/.pyenv/versions/3.13.7/lib/python3.13/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


Hybrid Late Delivery: DT + RF
              precision    recall  f1-score   support

           0       0.57      0.68      0.62     16308
           1       0.68      0.57      0.62     19796

    accuracy                           0.62     36104
   macro avg       0.63      0.63      0.62     36104
weighted avg       0.63      0.62      0.62     36104



### Late Delivery: DT + RF

| Metric | Class 0 (Not Late) | Class 1 (Late) |
|--------|-------------------|----------------|
| Precision | 0.57 | 0.68 |
| Recall | 0.68 | 0.57 |
| F1-Score | 0.62 | 0.62 |

DT + RF scored F1 0.62, below both base models. Two strong models in combination underperformed here, likely because their predictions are highly correlated.


In [152]:
pred = model_combinations(dt_late_delivery, xgb_late_delivery, w_dt_ld, w_xgb_ld, x_ld_test_scaled)
print('Hybrid Late Delivery: DT + XGB')
print(classification_report(y_ld_test, pred))


Hybrid Late Delivery: DT + XGB
              precision    recall  f1-score   support

           0       0.57      0.68      0.62     16308
           1       0.68      0.57      0.62     19796

    accuracy                           0.62     36104
   macro avg       0.63      0.63      0.62     36104
weighted avg       0.63      0.62      0.62     36104



/Users/kayodew/.pyenv/versions/3.13.7/lib/python3.13/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


### Late Delivery: DT + XGB

| Metric | Class 0 (Not Late) | Class 1 (Late) |
|--------|-------------------|----------------|
| Precision | 0.57 | 0.68 |
| Recall | 0.68 | 0.57 |
| F1-Score | 0.62 | 0.62 |

DT + XGB also scored F1 0.62. Despite XGBoost being the stronger partner here, the combination did not improve on either base model.


In [153]:
pred = model_combinations(rf_late_delivery, xgb_late_delivery, w_rf_ld, w_xgb_ld, x_ld_test_scaled)
print('Hybrid Late Delivery: RF + XGB')
print(classification_report(y_ld_test, pred))


/Users/kayodew/.pyenv/versions/3.13.7/lib/python3.13/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


Hybrid Late Delivery: RF + XGB
              precision    recall  f1-score   support

           0       0.80      0.13      0.22     16308
           1       0.58      0.97      0.72     19796

    accuracy                           0.59     36104
   macro avg       0.69      0.55      0.47     36104
weighted avg       0.68      0.59      0.50     36104



### Late Delivery: RF + XGB

| Metric | Class 0 (Not Late) | Class 1 (Late) |
|--------|-------------------|----------------|
| Precision | 0.80 | 0.58 |
| Recall | 0.13 | 0.97 |
| F1-Score | 0.22 | 0.72 |

**Best late delivery hybrid (tied with LR+XGB).** RF + XGB scored F1 0.72, but no hybrid beat the Decision Tree base model at 0.79. The best base model remains the stronger choice for late delivery prediction.


## Order Disruption Hybrid Models


In [154]:
w_lr_od   = 0.22
w_dt_od   = 0.31
w_rf_od   = 0.24
w_xgb_od  = 0.23


In [155]:
pred = model_combinations(lr_order_disruption, dt_disruption, w_lr_od, w_dt_od, x_od_test_scaled)
print('Hybrid Disruption: LR + DT')
print(classification_report(y_od_test, pred))


/Users/kayodew/.pyenv/versions/3.13.7/lib/python3.13/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


Hybrid Disruption: LR + DT
              precision    recall  f1-score   support

           0       0.93      0.51      0.66     33026
           1       0.10      0.61      0.18      3078

    accuracy                           0.52     36104
   macro avg       0.52      0.56      0.42     36104
weighted avg       0.86      0.52      0.62     36104



### Disruption: LR + DT

| Metric | Class 0 (Not Disrupted) | Class 1 (Disrupted) |
|--------|------------------------|---------------------|
| Precision | 0.93 | 0.10 |
| Recall | 0.51 | 0.61 |
| F1-Score | 0.66 | 0.18 |

LR + DT scored F1 0.18 on the disruption class. Both models struggle individually on this target (LR: 0.22, DT: 0.31), and combining them here produced the weakest hybrid result.


In [156]:
pred = model_combinations(lr_order_disruption, rf_disruption, w_lr_od, w_rf_od, x_od_test_scaled)
print('Hybrid Disruption: LR + RF')
print(classification_report(y_od_test, pred))


/Users/kayodew/.pyenv/versions/3.13.7/lib/python3.13/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


Hybrid Disruption: LR + RF
              precision    recall  f1-score   support

           0       0.93      0.97      0.95     33026
           1       0.33      0.17      0.22      3078

    accuracy                           0.90     36104
   macro avg       0.63      0.57      0.59     36104
weighted avg       0.88      0.90      0.89     36104



### Disruption: LR + RF

| Metric | Class 0 (Not Disrupted) | Class 1 (Disrupted) |
|--------|------------------------|---------------------|
| Precision | 0.93 | 0.33 |
| Recall | 0.97 | 0.17 |
| F1-Score | 0.95 | 0.22 |

LR + RF scored F1 0.22, matching LR's base score. The combination did not improve on either model alone.


In [157]:
pred = model_combinations(lr_order_disruption, xgb_disruption, w_lr_od, w_xgb_od, x_od_test_scaled)
print('Hybrid Disruption: LR + XGB')
print(classification_report(y_od_test, pred))


Hybrid Disruption: LR + XGB
              precision    recall  f1-score   support

           0       0.93      0.83      0.88     33026
           1       0.15      0.33      0.21      3078

    accuracy                           0.79     36104
   macro avg       0.54      0.58      0.54     36104
weighted avg       0.86      0.79      0.82     36104



### Disruption: LR + XGB

| Metric | Class 0 (Not Disrupted) | Class 1 (Disrupted) |
|--------|------------------------|---------------------|
| Precision | 0.93 | 0.15 |
| Recall | 0.83 | 0.33 |
| F1-Score | 0.88 | 0.21 |

LR + XGB scored F1 0.21, marginally below LR's base score of 0.22.


In [158]:
pred = model_combinations(dt_disruption, rf_disruption, w_dt_od, w_rf_od, x_od_test_scaled)
print('Hybrid Disruption: DT + RF')
print(classification_report(y_od_test, pred))


Hybrid Disruption: DT + RF
              precision    recall  f1-score   support

           0       0.93      0.51      0.66     33026
           1       0.10      0.61      0.18      3078

    accuracy                           0.52     36104
   macro avg       0.52      0.56      0.42     36104
weighted avg       0.86      0.52      0.62     36104



/Users/kayodew/.pyenv/versions/3.13.7/lib/python3.13/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
/Users/kayodew/.pyenv/versions/3.13.7/lib/python3.13/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


### Disruption: DT + RF

| Metric | Class 0 (Not Disrupted) | Class 1 (Disrupted) |
|--------|------------------------|---------------------|
| Precision | 0.93 | 0.10 |
| Recall | 0.51 | 0.61 |
| F1-Score | 0.66 | 0.18 |

DT + RF scored F1 0.18, below both base models. Despite DT being the strongest base model at 0.31, the combination underperformed.


In [159]:
pred = model_combinations(dt_disruption, xgb_disruption, w_dt_od, w_xgb_od, x_od_test_scaled)
print('Hybrid Disruption: DT + XGB')
print(classification_report(y_od_test, pred))


/Users/kayodew/.pyenv/versions/3.13.7/lib/python3.13/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


Hybrid Disruption: DT + XGB
              precision    recall  f1-score   support

           0       0.93      0.51      0.66     33026
           1       0.10      0.61      0.18      3078

    accuracy                           0.52     36104
   macro avg       0.52      0.56      0.42     36104
weighted avg       0.86      0.52      0.62     36104



### Disruption: DT + XGB

| Metric | Class 0 (Not Disrupted) | Class 1 (Disrupted) |
|--------|------------------------|---------------------|
| Precision | 0.93 | 0.10 |
| Recall | 0.51 | 0.61 |
| F1-Score | 0.66 | 0.18 |

DT + XGB also scored F1 0.18. No hybrid combination improved on the Decision Tree base model of 0.31 for disruption.


In [160]:
pred = model_combinations(rf_disruption, xgb_disruption, w_rf_od, w_xgb_od, x_od_test_scaled)
print('Hybrid Disruption: RF + XGB')
print(classification_report(y_od_test, pred))


/Users/kayodew/.pyenv/versions/3.13.7/lib/python3.13/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


Hybrid Disruption: RF + XGB
              precision    recall  f1-score   support

           0       0.93      0.74      0.82     33026
           1       0.13      0.40      0.19      3078

    accuracy                           0.71     36104
   macro avg       0.53      0.57      0.51     36104
weighted avg       0.86      0.71      0.77     36104



### Disruption: RF + XGB

| Metric | Class 0 (Not Disrupted) | Class 1 (Disrupted) |
|--------|------------------------|---------------------|
| Precision | 0.93 | 0.13 |
| Recall | 0.74 | 0.40 |
| F1-Score | 0.82 | 0.19 |

**Best disruption hybrid.** RF + XGB scored F1 0.19 - still the highest among hybrids but well below the Decision Tree base model at 0.31. No hybrid combination improved on the best base model for disruption.
